baseURL = 'https://oskarliew.com/'
languageCode = 'en-us'
title = 'Oskar Liew'

[params]
github = 'OskarLiew'
linkedin = 'oskarliew'
twitter = 'LiewOskar'
# mastodon = 'oskarliew'  # I don't really use mastodon

relatedtext = "Tags"
nextprev = true
taglist = true

[markup.highlight]
noClasses=false
