baseURL = 'https://oskarliew.com/'
languageCode = 'en-us'
title = 'Oskar Liew'

[params]
github = 'OskarLiew'
linkedin = 'oskarliew'
twitter = 'LiewOskar'
math = true
# mastodon = 'oskarliew'  # I don't really use mastodon

relatedtext = "Tags"
nextprev = true
taglist = true

[markup.highlight]
noClasses=false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
