baseURL = 'https://oskarliew.com/'
languageCode = 'en-us'
title = 'Oskar Liew'

[params]
github = 'OskarLiew'
linkedin = 'oskarliew'
twitter = 'LiewOskar'
mastodon = 'oskarliew'

relatedtext = "Tags"
